Added pundit, soft delete, background job
Evija-M/blog-prakse pull request #23
Opened 2022-06-06 06:51 UTC by Evija-M

Issues:
https://github.com/Evija-M/blog-prakse/issues/7 https://github.com/Evija-M/blog-prakse/issues/14 https://github.com/Evija-M/blog-prakse/issues/16 https://github.com/Evija-M/blog-prakse/issues/21 https://github.com/Evija-M/blog-prakse/issues/22 https://github.com/Evija-M/blog-prakse/issues/22
Ruby versija: 3.1.2
<img width="637" alt="Screenshot 2022-06-06 at 09 47 39" src="https://user-images.githubusercontent.com/85995321/172110103-9771b32e-d41c-4375-a495-5359977a8cbb.png">
<img width="482" alt="Screenshot 2022-06-06 at 09 49 20" src="https://user-images.githubusercontent.com/85995321/172110268-4c680e76-2cd7-4164-af85-5706f969a216.png">

2022-06-06 08:05 UTC, martinsspringis requested changes
1. Github CI nav nokonfigurēts
2. Arhivēšanas nebūtu jāinicializē pēc pieprasījuma bet reizi dienā, pameklē kādu scheduleri, kas to varētu izdarīt
3. Pielabo policy lai tas vairāk atbilst objektiem kam tas ir paredzēts
4. Pielabo pārējās minor lietiņas, plus ieliec .DS_Store gitignorē

2022-06-06 08:05 UTC, martinsspringis commented on .rubocop.yml
> +  Max: 50
Newline

2022-06-06 08:05 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    ArchiveArticlesJob.perform_now(@articles)
Šī job izsaukšana jāliek iekš scheduler, šeit nebūs pareizā vieta

2022-06-06 08:05 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    @article = Article.find(params[:id])
nav pielikts authorize

2022-06-06 08:05 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    @article.destroy_fully!
Domāju ka dzēšānai jālieto cita authorize metode unu dzēšanas metodes nosaukums nav apmierinošs.

2022-06-06 08:05 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +    authorize current_user, :signed_in?
šeit būtu jāliek šāds un jāsakārto tam CommentPolicy metode uz create:
`authorize Article`

2022-06-06 08:05 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +      flash[:error] = 'You cant restore this comment because article is still deleted'
Tulkojums

2022-06-06 08:05 UTC, martinsspringis commented on app/jobs/archive_articles_job.rb
> +  def perform(articles)
Domāju ka šai metodei var iztikt bez articles padošanas un atlasi veikt tieši metodē

`articles = Article.non_archived.older_than_week`

Un attiecīgi izveidot nepieciešamos scope iekš modeļa

2022-06-06 08:05 UTC, martinsspringis commented on app/models/article.rb
> +
To `ARCHIVED = 'archived'` labāk likt šeit augšā

2022-06-06 08:05 UTC, martinsspringis commented on app/policies/user_policy.rb
> +  # ??????
???

2022-06-06 08:05 UTC, martinsspringis commented on app/views/comments/show_user_deleted_comments.html.haml
> +%h1 Deleted comments
tulkojums

2022-06-09 06:32 UTC, martinsspringis requested changes
Pielabo piekomentētās lietiņas un saraksti testus visām izveidotajām fīčām :)

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/application_controller.rb
> +    flash[:alert] = 'You are not authorized to perform this action.'
locale

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    @deleted_articles = Article.only_deleted.where('user_id = ?', current_user.id)
Lietotāja rakstus meklē caur asociāciju

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    @article.destroy_fully!
Domāju, ka viņš nav jādzēš pilnībā, tāpēc labāk lieto parasto destroy

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +    authorize @article
pietiek ar vienu authorize...

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +    @deleted_comments = Comment.only_deleted.where('user_id = ?', current_user.id)
Lieto asociāciju

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +      flash[:error] = t('errors.unable_to_restore')
man liekas ka šādā keisā jau iekš policy vajag nomenedžēt, ka nevar restaurēt

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +    @comment.destroy_fully!
nevajag fully

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/users_controller.rb
> +    @users = User.with_deleted
kādēļ jārāda arī dzēstie

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/users_controller.rb
> +    authorize current_user, :index?
Diez vai šī būs pareizā autorizācija

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/articles_controller.rb
>    end
Iekš index nav izmantots policy scope lai atkarībā no lietotāja atrādītu visus vai tikai publiskos rakstus.

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    @articles = policy_scope(Article)
droši vien jāpamaina, jo policijam būtu jāļauj skatīt arī publiski pieejamos rakstus

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/articles_controller.rb
>      @articles = Article.all
Nav authorize

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/comments_controller.rb
> +    authorize current_user, :show?
Man izskatās ka šim būtu jābūt stingrākam nekā parastais shoow policy, jo skatīties jau komentāru var visi. ne?

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/users_controller.rb
> +    @users = User.with_deleted
+ policy_scope

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/users_controller.rb
> +    @user = authorize User.find(params[:id])
??

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/article_policy.rb
> +      @scope.where(user_id: @user.id)
šeit būs jāpārtaisa, ka atkarīgs no lietotāja būs atšķirīgs pieejamo rakstu loks

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/article_policy.rb
> +    user ? @article.user_id == user.id : false
droši vien arī dzēstu rakstu nevajadzētu labot

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/article_policy.rb
> +    user
`new?`

2022-06-09 06:32 UTC, martinsspringis commented on app/controllers/articles_controller.rb
> +    @article.destroy_fully!
nevajag delete action ja mums jau ir destroy, tas pārāk komplicēs sistēmu

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/article_policy.rb
> +    if user
Pietiek ar `@article.user == user `

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/article_policy.rb
> +    if article.status == 'private'
uztaisi vienā rindiņā

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/comment_policy.rb
> +    if user
vienā rindiņā

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/comment_policy.rb
> +    user ? comment.user_id == user.id : false
`comment.user == user` darītu to pašu ne?

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/nil_class_policy.rb
> +class NilClassPolicy < ApplicationPolicy
Kam šitais ir vajadzīgs?

2022-06-09 06:32 UTC, martinsspringis commented on app/policies/user_policy.rb
> +  def deleted?
Kam šī metode paredzēta?

2022-06-09 06:32 UTC, martinsspringis commented on app/views/articles/show.html.haml
> +  - if policy(@article).edit?
👍

2022-06-14 19:55 UTC, Evija-M commented on app/policies/user_policy.rb
> +  def deleted?
Iekš app/views/users/index.html.haml; adminam ir iespēja atjaunot dzēstos lietotājus.

2022-06-16 10:03 UTC, martinsspringis approved these changes
Good

2022-06-16 10:03 UTC, martinsspringis commented on spec/factories/comments.rb
> +    article { create :article }
arī pārtaisi uz `asssociation :article`

2022-06-16 14:03 UTC, merged